Repository Inkluzitron/Inkluzitron, pull requests merged in 2021-07, with the labels that each got.

#121 Nový způsob zpracování data a času.
  src/Inkluzitron/Services/TypeReaders/DateTimeTypeReader.cs
Labels: GrillBot - Port, enhancement

#122 change help message for PointsModule
  src/Inkluzitron/Modules/Points/PointsModule.cs
Labels: bugfix

#123 Added support for UserTypeReader to HuggingModule
  src/Inkluzitron/Modules/HuggingModule.cs
Labels: bugfix

#130 Předěláno skloňování do string template
  src/Inkluzitron/Models/BdsmTraitOperationCheck.cs
  src/Inkluzitron/Models/Settings/BdsmTraitOperationCheckTranslations.cs
  src/Inkluzitron/Modules/SystemModule.cs
  src/Inkluzitron/Services/KisService.cs
  src/Inkluzitron/Services/PointsService.cs
  src/Inkluzitron/Services/RuntimeService.cs
  src/Inkluzitron/Utilities/FormatByValue.cs
  src/Inkluzitron/appsettings.json
Labels: enhancement
