Repository Inkluzitron/Inkluzitron, pull requests merged in 2021-04, with the labels that each got.

#14 Implementace příkazu uptime.
  src/Inkluzitron/Extensions/TimeSpanExtensions.cs
  src/Inkluzitron/Modules/SystemModule.cs
Labels: new feature

#16 Robustnější matchování automatických zpráv
  src/Inkluzitron/Modules/ReplyModule.cs
Labels: bug

#20 Opravy chyb nalezených v produkčním prostředí
  src/Dockerfile
  src/Inkluzitron/Extensions/ImageExtensions.cs
  src/Inkluzitron/Modules/ImagesModule.cs
Labels: bug

#29 Remove Random initialization and hardcoded path to gif
  src/Inkluzitron/Modules/MockingModule.cs
Labels: bug

#37 Docker opět zklamal a choval se jinak
  src/Inkluzitron/Modules/ImagesModule.cs
Labels: bug

#38 Změna algoritmu generování mocking zprávy
  src/Inkluzitron/Modules/ImagesModule.cs
  src/Inkluzitron/Modules/MockingModule.cs
Labels: enhancement
