Repository Inkluzitron/Inkluzitron, pull requests merged in 2021-06, with the labels that each got.

#84 Inkrementace bodů stylem karmy
  src/Inkluzitron/Models/Settings/BotSettings.cs
  src/Inkluzitron/Modules/ImagesModule.cs
  src/Inkluzitron/Services/PointsService.cs
  src/Inkluzitron/appsettings.json
Labels: enhancement

#89 Oprava pro stats command, přidán souhlas s obrázkovými příkazy
  src/Inkluzitron/Data/Entities/User.cs
  src/Inkluzitron/Enums/BdsmTraitOperationCheckResult.cs
  src/Inkluzitron/Enums/CommandConsent.cs
  src/Inkluzitron/Extensions/BotDatabaseContextExtensions.cs
  src/Inkluzitron/Migrations/20210607095423_CommandConsent.Designer.cs
  src/Inkluzitron/Migrations/20210607095423_CommandConsent.cs
  src/Inkluzitron/Migrations/20210607112702_RemoveUserTimestamp.Designer.cs
  src/Inkluzitron/Migrations/20210607112702_RemoveUserTimestamp.cs
  src/Inkluzitron/Migrations/20210607112801_ReaddUserTimestampWithTrigger.Designer.cs
  src/Inkluzitron/Migrations/20210607112801_ReaddUserTimestampWithTrigger.cs
  src/Inkluzitron/Migrations/BotDatabaseContextModelSnapshot.cs
  src/Inkluzitron/Models/BdsmTraitOperationCheck.cs
  src/Inkluzitron/Models/Settings/BdsmTestOrgSettings.cs
  src/Inkluzitron/Models/Settings/BdsmTraitOperationCheckTranslations.cs
  src/Inkluzitron/Modules/BdsmTestOrg/BdsmModule.cs
  src/Inkluzitron/Modules/ImagesModule.cs
  src/Inkluzitron/Modules/Points/PointsModule.cs
  src/Inkluzitron/Services/UserBdsmTraitsService.cs
  src/Inkluzitron/Utilities/Patiently.cs
  src/Inkluzitron/appsettings.json
Labels: bug, enhancement, new feature

#95 Hotfix na escape vypisovaných znaků
  src/Inkluzitron/Extensions/MagickImageExtensions.cs
  src/Inkluzitron/Services/PointsService.cs
Labels: bug

#103 Výpis chybových zpráv do Discord roomky
  src/Inkluzitron/Models/Settings/BotSettings.cs
  src/Inkluzitron/Program.cs
  src/Inkluzitron/Services/ChannelLogger/ChannelLogger.cs
  src/Inkluzitron/Services/ChannelLogger/ChannelLoggerConfiguration.cs
  src/Inkluzitron/Services/ChannelLogger/ChannelLoggerExtensions.cs
  src/Inkluzitron/Services/ChannelLogger/ChannelLoggerProvider.cs
  src/Inkluzitron/appsettings.json
Labels: new feature

#104 Zjednodušení testu - jen jeden výsledek na uživatele
  src/Inkluzitron/Modules/BdsmTestOrg/BdsmModule.cs
  src/Inkluzitron/Modules/BdsmTestOrg/EmbedBuilderExtensions.cs
  src/Inkluzitron/Modules/BdsmTestOrg/QuizEmbedManager.cs
  src/Inkluzitron/Modules/BdsmTestOrg/QuizEmbedMetadata.cs
Labels: enhancement

#105 Implementace získávání bodů z KISu. Verze a notifikace verze.
  .dockerignore
  Dockerfile
  docker-compose.yml
  environment.template.env
  src/Inkluzitron/Data/BotDatabaseContext.cs
  src/Inkluzitron/Data/Entities/User.cs
  src/Inkluzitron/Extensions/SocketGuildExtensions.cs
  src/Inkluzitron/Inkluzitron.csproj
  src/Inkluzitron/Migrations/20210624150006_KisPoints.Designer.cs
  src/Inkluzitron/Migrations/20210624150006_KisPoints.cs
  src/Inkluzitron/Migrations/20210624164921_UsersKisNicknameIndex.Designer.cs
  src/Inkluzitron/Migrations/20210624164921_UsersKisNicknameIndex.cs
  src/Inkluzitron/Migrations/BotDatabaseContextModelSnapshot.cs
  src/Inkluzitron/Models/Kis/KisPrestigeResult.cs
  src/Inkluzitron/Models/Kis/LeaderboardItem.cs
  src/Inkluzitron/Models/Settings/KisSettings.cs
  src/Inkluzitron/Modules/Points/PointsModule.cs
  src/Inkluzitron/Modules/SystemModule.cs
  src/Inkluzitron/Modules/UserModule.cs
  src/Inkluzitron/Program.cs
  src/Inkluzitron/Services/ImagesService.cs
  src/Inkluzitron/Services/KisService.cs
  src/Inkluzitron/Services/PointsService.cs
  src/Inkluzitron/Services/RuntimeService.cs
  src/Inkluzitron/Services/UsersService.cs
  src/Inkluzitron/appsettings.json
  src/environment.template.env
Labels: new feature

#106 Oprava chyby, kdy si uživatel mohl vícekrát stáhnout body
  src/Inkluzitron/Services/PointsService.cs
Labels: bug

#115 Change autoreply to `PR`
  src/Inkluzitron/Modules/ReplyModule.cs
Labels: bugfix

#116 Case insensitive nickname match + kokot
  src/Inkluzitron/Services/TypeReaders/UserTypeReader.cs
Labels: bugfix, enhancement

#118 Úprava peepolove obrázku (hlavně menší)
  src/Inkluzitron/Resources/Peepolove/body.png
  src/Inkluzitron/Resources/Peepolove/hands.png
  src/Inkluzitron/Services/ImagesService.cs
Labels: enhancement

#119 Odstranění nevyužívaného sloupce Users.Points v db
  src/Inkluzitron/Migrations/20210630121000_UsersPointsRemove.Designer.cs
  src/Inkluzitron/Migrations/20210630121000_UsersPointsRemove.cs
Labels: bugfix
